default: node.h node.cpp minheap.h minheap.cpp hufftree.h hufftree.cpp filereader.h filereader.cpp main.cpp
	g++ -std=c++11 -Wall -Wextra -pedantic -g node.cpp minheap.cpp hufftree.cpp filereader.cpp main.cpp
 -o huff
